---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: op-scim-bridge
spec: 
{{ .Values.storageSpec | toYaml | trim | indent 2 }}
