---
replicaCount: 1
accountdomain: example.com
scimsessionPath: /secret/scimsession

storageSpec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: standard

redis:
  enabled: true
  usePassword: false
  cluster:
    enabled: true
    slaveCount: 1
    